# Generated by Django 5.2.17 on 2026-09-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0037_bot_moderation_illicit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="survey_context_in_followup",
            field=models.BooleanField(
                default=True,
                help_text="If true, survey context is also included when generating idle follow-up messages. Only has an effect when a survey context preamble is set.",
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="survey_context_preamble",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Sentence introducing the participant's pre-conversation survey answers to the model, e.g. 'The participant answered these questions before talking to you:'. LEAVE BLANK to append nothing — that is how a control condition is configured.",
            ),
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("survey_id", models.CharField(max_length=255)),
                ("participant_id", models.CharField(max_length=255)),
                (
                    "answers",
                    models.JSONField(
                        default=list,
                        help_text="List of {'question': ..., 'answer': ...} in the order asked. Neither the number of questions nor the length of an answer is capped.",
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("survey_id", "participant_id")},
            },
        ),
    ]
