# Generated by Django 5.2.17 on 2026-09-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0038_bot_survey_context_in_followup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="survey_context",
            field=models.JSONField(
                blank=True,
                help_text="Snapshot of the participant's survey answers as used by THIS conversation, copied from SurveyResponse at init. A copy rather than a link, so the record stays reproducible if the survey tool later overwrites the answers. Null means no answers were found for this participant.",
                null=True,
            ),
        ),
    ]
