# Generated by Django 5.2.17 on 2026-09-15 19:29

from django.db import migrations, models

import chatbot.models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0039_conversation_survey_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyIngestToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=chatbot.models.generate_survey_token,
                        editable=False,
                        help_text="Generated automatically. Copy this into your survey tool as the X-Survey-Token header.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        help_text="What this token is for, e.g. 'Stress study, wave 1'. Only for your own reference.",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to revoke this token without deleting the record. A revoked token is rejected immediately.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Survey ingest token",
                "ordering": ("-created_at",),
            },
        ),
    ]
