# Generated by Django 5.2.17 on 2026-10-08 18:00

from django.db import migrations, models


def enable_where_a_preamble_was_set(apps, schema_editor):
    """
    Preserve behaviour for bots configured under the old rule.

    Survey context used to be switched on by typing something into
    survey_context_preamble. Adding an explicit checkbox that defaults to off
    would silently disable every bot already relying on that, turning live
    treatment participants into controls without a trace. So anything with a
    preamble keeps working.
    """
    Bot = apps.get_model("chatbot", "Bot")
    Bot.objects.exclude(survey_context_preamble="").exclude(
        survey_context_preamble=None
    ).update(survey_context_enabled=True)


def disable_all(apps, schema_editor):
    """
    Reverse: the column is about to be dropped, so there is nothing to undo.
    The old rule reads the preamble, which this migration never touched.
    """
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0040_surveyingesttoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="survey_context_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Give this bot the participant's pre-conversation survey answers. This checkbox is the switch: a blank preamble below does NOT turn it off. Leave unticked for a control condition.",
            ),
        ),
        migrations.AlterField(
            model_name="bot",
            name="survey_context_preamble",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional sentence introducing the answers to the model, e.g. 'The participant answered these questions before talking to you:'. Leave blank to pass the answers with no introduction. This does not switch the feature on or off — the checkbox above does.",
            ),
        ),
        migrations.RunPython(
            enable_where_a_preamble_was_set,
            disable_all,
        ),
    ]
